config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'users/new'

  root 'pages#home'

  get 'pages/home' 

  get 'pages/contact'

  get 'pages/about'
  get 'pages/help'
  get 'home' => 'pages#home'
  get 'younes' => 'pages#home'
  get 'contact' => 'pages#contact'
  get 'help' => 'pages#help'
  get 'about' => 'pages#about'

  get 'signup' => 'users#new'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base

	attr_accessor :password

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :nom, presence: true, :length   => { :maximum => 50 }
	validates :email, presence: true,
	:format   => { :with => email_regex },
	:uniqueness => { :case_sensitive => false }
	# Crée automatique l'attribut virtuel 'password_confirmation'.
    validates :password, presence: true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }


    before_save :encrypt_password

	    # Retour true (vrai) si le mot de passe correspond.
	def has_password?(password_soumis)
	    # Compare encrypted_password avec la version cryptée de
	    # password_soumis.
	    encrypted_password == encrypt(password_soumis)
	end

	def self.authenticate(email, submitted_password)
	    user = find_by_email(email)
	    return nil  if user.nil?
	    return user if user.has_password?(submitted_password)
  	end


	private

	    def encrypt_password
	      self.salt = make_salt if new_record?
	      self.encrypted_password = encrypt(password)
	    end

	    def encrypt(string)
	      secure_hash("#{salt}--#{string}")
	    end

	    def make_salt
	      secure_hash("#{Time.now.utc}--#{password}")
	    end

	    def secure_hash(string)
	      Digest::SHA2.hexdigest(string)
	    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @titre = "Accueil"
    @testVariable="truite"
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre = "À Propos"
  end
  def help
    @title = "Aide"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  def show
  	@user = User.find(params[:id])
  	@titre = @user.nom
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

	#return a title based on a page
	def title
		base_title="My App"
		if @titre.nil?
			base_title
		else
			"#{base_title} | #{@titre}"
		end
	end






end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<header>
		<%= image_tag("truite.png", :alt => "Application exemple", :class => "testPictureSize") %>
		<div class="menu">
			<ul class="nav nav-pills">
		  		<li role="presentation" class="active">
		  			<%= link_to "Accueil", home_path %>
		  		</li>
		  		<li role="presentation">
		  			<%= link_to "APropos", about_path %>
		  		</li>
		  		<li role="presentation">
		  			<li><%= link_to "Inscription", '/pages/register' %></li>
		  		</li>
			</ul>
		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/menu' %>
	<%= render 'pages/testNaze' %>

<%= yield %>


      <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/_testNaze.html.erb
<h1>1</h1>

app/views/pages/about.html.erb


    <h1>Simple App</h1>
    <p>
      Ceci est la page d'accueil de l'Application Exemple du <%= @testVariable %>
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>.
    </p>
 

app/views/pages/contact.html.erb
  
    <h1>Simple App</h1>
    <p>
      Ceci est la page d'accueil de l'Application Exemple du <%= @testVariable %>
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>.
    </p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails Tutorial sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette application exemple, consultez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
    <h1>Simple App</h1>
    <p>
      Ceci est la page d'accueil de l'Application Exemple du <%= @testVariable %>
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>.
    </p>

    <%= link_to "S'inscrire&nbsp;!", signup_path, :class => "btn btn-default" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        
        <%= @user.nom %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Nom</strong> <%= @user.nom %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>



